PREFIX brick: <http://buildsys.org/ontologies/Brick#>
PREFIX sim: <http://ti.rw.fau.de/sim#>

CONSTRUCT {
    ?occupant a sim:Occupant ;
              sim:workplace ?room .
} WHERE {
    ?room a brick:Room .
    BIND (iri(concat(str(?room), "#occupant")) AS ?occupant)
}