PREFIX : <http://ti.rw.fau.de/sim#>

DELETE {
    GRAPH <sim> {
        ?sim :currentIteration ?oldIt ;
             :currentTime ?oldTime .
    }
} INSERT {
    GRAPH <sim> {
        ?sim :currentIteration ?it ;
             :currentTime ?time .
    }
} WHERE {
    ?sim :currentIteration ?oldIt .
    BIND (?oldIt + 1 AS ?it)
    OPTIONAL {
        ?sim :currentTime ?oldTime ;
             :timeslotDuration ?duration .
        BIND (:after(?time, ?duration) AS ?time)
    }
}