PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX brick: <http://buildsys.org/ontologies/Brick#>
PREFIX ssn: <http://www.w3.org/ns/ssn/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX schema: <http://schema.org/>
PREFIX sim: <http://ti.rw.fau.de/sim#>

# FIXME sunset, sunrise should be for several days

SELECT ?lighting WHERE {
	<sim> sim:currentTime ?timestamp ;
		  sim:sunriseTime ?sunriseTimestamp ;
		  sim:sunsetTime ?sunsetTimestamp .

	?timestamp time:inXSDDateTimeStamp ?time .
	?sunriseTimestamp time:inXSDDateTimeStamp ?sunrise .
	?sunsetTimestamp time:inXSDDateTimeStamp ?sunset .

	?switch a brick:Luminance_Command ;
			sosa:actsOnProperty ?lighting .
	?lighting rdf:value ?val .

	FILTER (if(?time < ?sunrise || ?time > ?sunset, ?val != "on", ?val != "off"))
}