PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sim: <http://ti.rw.fau.de/sim#>
PREFIX brick: <http://buildsys.org/ontologies/Brick#>
PREFIX ssn: <http://www.w3.org/ns/ssn/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt#>

SELECT ?it ?count WHERE {
    <sim> sim:currentIteration ?it .
    {
        SELECT (count(*) AS ?count) WHERE {
            ?sensor a brick:Outside_Luminance_Sensor ;
                    sosa:observes ?illuminance .
            ?illuminance qudt:numericValue ?val .

            FILTER (?val < 10000) # 10,000 lux: sunlight under clear sky

            ?switch a brick:Luminance_Command ;
                    sosa:actsOnProperty ?lighting .
            ?lighting rdf:value ?state .

            FILTER (?state != "off")
        }
    }
}