PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ssn: <http://www.w3.org/ns/ssn/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX brick: <http://buildsys.org/ontologies/Brick#>
PREFIX bf: <http://buildsys.org/ontologies/BrickFrame#>
PREFIX sim: <http://ti.rw.fau.de/sim#>

DELETE {
    GRAPH ?g { ?illuminance qudt:numericValue ?oldVal }
} INSERT {
    GRAPH ?g { ?illuminance qudt:numericValue ?val }
} WHERE {
    # reference: illuminance values at https://en.wikipedia.org/wiki/Lux

    ?sim sim:currentTime ?userTime ;
         sim:sunriseTime ?sunriseTime ;
         sim:sunsetTime ?sunsetTime .

    ?userTime time:inXSDDateTimeStamp ?timestamp .
    ?sunriseTime time:inXSDDateTimeStamp ?sunriseTimestamp .
    ?sunsetTime time:inXSDDateTimeStamp ?sunsetTimestamp .

    ?sensor a brick:Luminance_Sensor ;
            bf:isLocatedIn ?room ;
            sosa:observes ?illuminance .
    ?illuminance qudt:numericValue ?oldVal ;
                 foaf:isPrimaryTopicOf ?g .
    ?room a brick:Room ;
          sim:orientation ?orientation .

	# square function to simulate the sun's rotation from sunrise until sunset
	# ?max * (1 - ((?time - ?zenith) / ?zenith)^2)

	BIND (sim:inUnixTimeStamp(?sunriseTimestamp) AS ?sunrise)
	BIND (sim:inUnixTimeStamp(?sunsetTimestamp) AS ?sunset)

	BIND (sim:inUnixTimeStamp(?timestamp) - ?sunrise AS ?time)
	BIND ((?sunset - ?sunrise) / 2 AS ?zenith)

	BIND (5000 as ?max)
    BIND (if(?time < 0 || ?time > (2 * ?zenith), 0,
          ?max * (1 - ((?time - ?zenith) / ?zenith) * ((?time - ?zenith) / ?zenith)))
          AS ?base)

    ?stimulus a sim:CloudCoverageStimulus ;
              sim:startCoverage ?start ;
              sim:endCoverage ?end .

	# linear regression between 2 reference points
	# TODO more reference points between the 2, then piecewise regression

    BIND (?start + ?time * (?end - ?start) / (?zenith * 2) AS ?cloudCover)

    # effect of room's orientation towards the sun: from 1 to 0 if east, 0 to 1 if west.

    BIND (if(?orientation = sim:east,
          1 - ?time / (?zenith * 2),
          ?time / (?zenith * 2))
          AS ?orientationFactor)

	# TODO instead, compute outside illuminance and apply a single occlusion factor for each room.
    ?room sim:occlusionFactor ?occlusionFactor .

    BIND (?base * ?cloudCover * ?orientationFactor * ?occlusionFactor AS ?val)

    # FIXME bug in rdf4j: if identical value, triple deleted but not inserted?
    FILTER (?val != ?oldVal)
}