PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sim: <http://ti.rw.fau.de/sim#>
PREFIX brick: <http://buildsys.org/ontologies/Brick#>
PREFIX bf: <http://buildsys.org/ontologies/BrickFrame#>
PREFIX ssn: <http://www.w3.org/ns/ssn/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt#>

#SELECT ?it ?count WHERE {
#    <sim> sim:currentIteration ?it .
#    {
#        SELECT (count(*) AS ?count) WHERE {
#            ?sensor a brick:Luminance_Sensor ;
#                    bf:isLocatedIn ?room ;
#                    sosa:observes ?illuminance .
#            ?illuminance qudt:numericValue ?val .
#            ?room a brick:Room .
#
#            FILTER (?val < 500) # 500 lux: office lighting
#        }
#    }
#}

SELECT ?it ?f23 ?wc WHERE {
    <sim> sim:currentIteration ?it .
    {
        SELECT ?f23 WHERE {
            ?sensor a brick:Luminance_Sensor ; bf:isLocatedIn <Room_SOR42_F_23> ; sosa:observes ?illuminance .
            ?illuminance qudt:numericValue ?f23 .
        } LIMIT 1
    }
    {
        SELECT ?wc WHERE {
            ?sensor a brick:Luminance_Sensor ; bf:isLocatedIn <Room_SOR42_F_WC> ; sosa:observes ?illuminance .
            ?illuminance qudt:numericValue ?wc .
        } LIMIT 1
    }
}