PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ssn: <http://www.w3.org/ns/ssn/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX brick: <http://buildsys.org/ontologies/Brick#>
PREFIX bf: <http://buildsys.org/ontologies/BrickFrame#>
PREFIX sim: <http://ti.rw.fau.de/sim#>

DELETE {
    GRAPH ?g { ?lighting rdf:value ?oldState }
} INSERT {
    GRAPH ?g { ?lighting rdf:value ?state }
    ?lighting sim:initialValue ?state
} WHERE {
    ?switch a brick:Luminance_Command ;
            sosa:actsOnProperty ?lighting .
    ?lighting rdf:value ?oldState ;
              foaf:isPrimaryTopicOf ?g .
    BIND (if(sim:rand(?lighting) < 0.5, "on", "off") AS ?state)
};

DELETE {
    GRAPH ?g { ?lighting rdf:value ?oldState }
    ?lighting sim:initialValue ?state
} INSERT {
    GRAPH ?g { ?lighting rdf:value "on" }
} WHERE {
    ?switch a brick:Luminance_Command ;
            sosa:actsOnProperty ?lighting .
    ?lighting rdf:value ?oldState ;
              foaf:isPrimaryTopicOf ?g .

	?room a ?class ;
	      bf:hasPoint ?switch .
	?class rdfs:subClassOf* <PersonalHygiene> .
};