PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX brick: <http://buildsys.org/ontologies/Brick#>
PREFIX bframe: <http://buildsys.org/ontologies/BrickFrame#>
PREFIX ssn: <http://www.w3.org/ns/ssn/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX sim: <http://ti.rw.fau.de/sim#>

SELECT ?lighting WHERE {
	?switch a brick:Luminance_Command ;
			sosa:actsOnProperty ?lighting .

	{
		?lighting rdf:value ?val .
		?room a ?toiletLike ;
			  bframe:hasPoint ?switch .
		?toiletLike rdfs:subClassOf* <PersonalHygiene> .
		FILTER (?val != "off")
	}
	UNION
	{
		?lighting rdf:value ?val ;
				  sim:initialValue ?initVal .
		?room a brick:Room ;
		      bframe:hasPoint ?switch .
		FILTER NOT EXISTS {
			?room a ?toiletLike .
			?toiletLike rdfs:subClassOf* <PersonalHygiene> .
		}
		FILTER (?val != ?initVal)
	}
}